### ISSUE TITLE
Cannot run without installing 'Go'

### ISSUE THREAD

**Issue by kelseyhuse30** [xyzst/atx-utilities#1]
This isn't really an 'issue' that needs resolved, I guess, but I wanted to let you know I was trying to run the steps in the README for `pants` (says no need to install Go) but don't think that's the case :(

<img width="1033" alt="image" src="https://user-images.githubusercontent.com/21069635/189150949-d75f1ff4-e62b-41ac-8950-07f9f8befa5f.png">

**Comment by xyzst** [comment]
@kelseyhuse30 replaced pants build with docker, see these instructions:

https://github.com/xyzst/atx-utilities/blob/main/README.md#run-w-docker-go-not-needed

let me know if there are any issues!
